# Generated by Django 3.0.2 on 2020-01-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_hero', models.CharField(max_length=250, verbose_name='Название')),
                ('image_hero', models.ImageField(blank=True, default='', upload_to='mainpage/hero', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главные',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_why', models.CharField(max_length=150, verbose_name='Название')),
                ('text_why', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Почему мы?',
                'verbose_name_plural': 'Почему мы?',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_work', models.ImageField(blank=True, default='', upload_to='mainpage/work', verbose_name='Фотография')),
                ('text_work', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работа',
            },
        ),
    ]
